[[redirects]]
  from = "https://quickrideghana.com/*"
  to = "https://rydonghana.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.quickrideghana.com/*"
  to = "https://rydonghana.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.rydonghana.com/*"
  to = "https://rydonghana.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/book"
  to = "/book.html"
  status = 200

[[redirects]]
  from = "/get"
  to = "/get.html"
  status = 200

[[redirects]]
  from = "/drive"
  to = "/drive.html"
  status = 200

[[redirects]]
  from = "/restaurant"
  to = "/restaurant.html"
  status = 200
